### ISSUE TITLE
RQt improvement list

### ISSUE THREAD

**Issue by danipurwadi** [yonahbox/Yonah_ROS_packages#29]
Features to improve:
- [x] Adding new identifiers
- [x] Editing current identifiers
- [x] Make custom RegEx for the identifier fields to prevent user typo-ing etc
- [x] Make checklist window unique to each aircraft
- [x] Sync the changing of command combo box with the change of tab
- [x] Automatic active aircraft detection
- [x] Double confirm on ARM and DISARM button to avoid accidental double clicks
- [x] Enable keyboard shortcut for disarm
- [x] Consider re-structuring the RQt code using suggestion Rumesh pointed out
- [x] Improve ping feature (as of now it only sends simple ping message)
- [x] Separate the MAVROS subscriber list
- [x] Restructure the UI to enable more buttons to be put in place 
- [x] Code optimisation
- [x] Opening ROS logs feature
- [x] Only show active aircrafts on Display
- [x] Add button for Syncing methods
- [x] Add restore_settings function
- [ ] Receive valid id from launch
- [ ] Write valid id from RQt
- [ ] Waypoint Editor feature
- [ ] Check for sms credits / other links credits warning message
- [x] Waypoint load diff from mission load (change mission/waypoint load + input_text[0])
- [x] Mission Next button -> send mission next
- [x] Pause and Resume button
- [ ] Sync identifiers 
- [ ] Finished syncing

Notes for adding identifiers
- Adding new planes --> label(NEMO1), phone no, IMEI, serial number
- Editing planes --> select label from existing list, and then new info

Debug Issues
- [x] Arm warning window popped up regardless of checklist completion status
- [x] Arm warning window is not unique to each checklist window
- [x] Command window code executes before user input
- [x] Change Mode command is rejected by gnd_despatcher
- [x] Time calculation 
- [x] Identifiers windows next menu mechanism -- make it such that upon cancel it shows the previous window
- [x] Changing aircraft ID on edit identifiers throws error
- [x] Closing window on the change identifiers feature is not optimal (windows didn't close properly)
- [x] Change the AC name from just the ID to AC label instead
- [x] On demand format to add the id and split the message. Also change data to data.data
Side-notes:
- [x] Make RQt window scalable (or set a min height)
- [x] Add alt+f4 as a shortcut for RQt
- [x] self.side on command_window could be optimised
- [x] self.current_identifiers can be optimised
- [x] Variable naming can be better (some variable names are copy pasted from another function so its not very representative)
- [x] Tidy up import statements
- [x] statustext header is now only showing the aircraft ID (add number)

**Comment by yonahbox** [comment]
Error thrown by rqt when receiving a regular payload message over the SBD link (server method):

```
Traceback (most recent call last):
  File "/home/goodness/Yonah_ROS_packages/ogc_ws/src/rqt_mypkg/src/rqt_mypkg/my_module.py", line 226, in gps_display
    rospy.logdebug_throttle(30, "[AC {} GPS display] {}".format(int(id), data))
NameError: global name 'data' is not defined
[rqt_mypkg-6] process has died [pid 10207, exit code 1, cmd /opt/ros/kinetic/lib/rqt_gui/rqt_gui __name:=rqt_mypkg __log:=/home/goodness/.ros/log/7a4efeec-bb67-11ea-8ab8-a0a8cdd16262/rqt_mypkg-6.log].
log file: /home/goodness/.ros/log/7a4efeec-bb67-11ea-8ab8-a0a8cdd16262/rqt_mypkg-6*.log
```

**Comment by danipurwadi** [comment]
> Error thrown by rqt when receiving a regular payload message over the SBD link (server method):
> 
> ```
> Traceback (most recent call last):
>   File "/home/goodness/Yonah_ROS_packages/ogc_ws/src/rqt_mypkg/src/rqt_mypkg/my_module.py", line 226, in gps_display
>     rospy.logdebug_throttle(30, "[AC {} GPS display] {}".format(int(id), data))
> NameError: global name 'data' is not defined
> [rqt_mypkg-6] process has died [pid 10207, exit code 1, cmd /opt/ros/kinetic/lib/rqt_gui/rqt_gui __name:=rqt_mypkg __log:=/home/goodness/.ros/log/7a4efeec-bb67-11ea-8ab8-a0a8cdd16262/rqt_mypkg-6.log].
> log file: /home/goodness/.ros/log/7a4efeec-bb67-11ea-8ab8-a0a8cdd16262/rqt_mypkg-6*.log
> ```

Noted on that, fixed the issue on the commit d1c3afcce3dd65ed48453e492780ec664eef9df3

**Comment by disgruntled-patzer** [comment]
Error thrown by rqt when I try to launch the Yonah rqt plugin from the rqt main page:

```
PluginManager._load_plugin() could not load plugin "rqt_mypkg/My Plugin":
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 61, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 106, in load
    return class_ref(plugin_context)
  File "/home/lenovo/Yonah_ROS_packages/ogc_ws/src/rqt_mypkg/src/rqt_mypkg/my_module.py", line 87, in __init__
    self.CommandWindow = CommandWindow(self.active_aircrafts)
  File "/home/lenovo/Yonah_ROS_packages/ogc_ws/src/rqt_mypkg/src/rqt_mypkg/command_window.py", line 74, in __init__
    self.custom_ping_list.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```

* OS: Ubuntu 20.04
* Launch file used: ogc_gndtest.launch
* Nodes: Tele, SMS, SBD (gnd), gnd despatcher, gnd statustext, identifiers, rqt
* Context: Was trying to test the OGC ground system's intelligent link switching behaviour

**Comment by danipurwadi** [comment]
Closing the issue as most of the development work in rqt is done. There are a few items in the checklist that has not been checked, however, those involve other parts in the ogc system which is still under development or it's too big of a project to be tackled in this iteration.
